name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run app in background
        run: |
          nohup java -jar ./artifacts/app-order.jar &
          sleep 10  # Ждем запуска приложения
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests with headless
        run: |
          ./gradlew test -Dchromeoptions.prefs=profile.password_manager_leak_detection=false
        env:
          HEADLESS: true