name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        run: |
          java -jar ./artifacts/app-order.jar &
          # Wait for SUT to start (check every 5 seconds, timeout 60 seconds)
          while ! curl -s http://localhost:9999 > /dev/null; do
            echo "Waiting for SUT to start..."
            sleep 5
          done
          echo "SUT is up and running!"
      - name: Build with Gradle
        run: ./gradlew test -Dselenide.headless=true --info # Укажите -Dselenide.headless=true, только если нужно явно
